name: Lint, Test and Deploy
on: 
  issues:
    types: [opened]
jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "titulo:${{ github.event.title }} data:${{ github.event.updated_at }} url:${{github.event.url}}"
