name: Lint, Test and Deploy
on: 
  issues:
    types: [opened]
jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "titulo->${{ github.event.issue.title }} data->${{ github.event.issue.updated_at }} url->${{github.event.issue.url}}"
